import java.util.scanner;
class Exception3
{
    public static void main(String Arg[])
    {
        try
    }
    system.out.println("inside try block");
    scanner sobj = new sacnner (System.in);
    int Arr[] = { 10,20,30,40,50};
    system.out.println("enter the index number");
    int i = sobj.nextInt();
    system.out.println(Arr[i]);
{
   catch (ArrayIndexOutBoundExcepatin3obj)
   {
    system.out.println("inside Catch block");
   }
   finally 
   {
    system.out.println("inside Finally block");
   }
   
   system.out.println("end of code");
   
}
}